### ISSUE TITLE
Benchmarking Testing

### ISSUE THREAD

**Issue by rigelrozanski** [jblindsay/whitebox-geospatial-analysis-tools#28]
It would be useful to have a series of benchmarking utilities to test the efficiency of routines, especially useful when modifying or optimizing existing routines. http://stackoverflow.com/questions/8423789/benchmarking-inside-java-code

**Comment by jblindsay** [comment]
I do not plan on investing further development effort in Java (i.e. major feature development), given the plan to eventually transition away from the Java platform for the Whitebox project described in #27. At this point, there are several disadvantages to developing for the JVM, not the least of which is the spotty and inconsistent support for Java in recent versions of Windows and lack of support in older versions of the operating system. Most of the advantages with originally choosing Java (namely the cross-platform support offered by the JVM) have been outweighed by the numerous disadvantages.
