### ISSUE TITLE
Is it possible to use this applications APIs in order to develop standalone apps?

### ISSUE THREAD

**Issue by am2222** [jblindsay/whitebox-geospatial-analysis-tools#29]
Hi,
It seems there was not any advertisements around this application. It is first time that I have seen this application since last few years and I am glad to find it.
My question is simple 
Is it possible to use this applications APIs in order to develop standalone apps?

**Comment by jblindsay** [comment]
Hello,


I'm afraid that at the moment it's not so easy to do this. If it is a matter of wanting to call Whitebox GAT plugin tools from outside of the Whitebox user-interface, something that has been brought up quite a few times in the past, then we're currently working on a design that will make that considerably easier. The latest version of Whitebox (3.4.0) contains several examples of plugin tools that are written in either Rust or Go programming languages and are compiled to native executables. These, are certainly callable from outside the Whitebox interface. Future plans for the project involve converting existing tools to this format to further allow the access of Whitebox functionality from scripting languages without the need for the full Whitebox software.


Regards,


John


John Lindsay, PhD

Room 346, Hutt Building,

Department of Geography,

The University of Guelph,

E-mail: jlindsay@uoguelph.ca

Phone: (519) 824-4120 ext. 56074

Web: http://www.uoguelph.ca/geography/faculty/lindsay-john

Research page: http://www.uoguelph.ca/~hydrogeo/

Whitebox GAT: http://www.uoguelph.ca/~hydrogeo/Whitebox/index.html


________________________________

**Comment by am2222** [comment]
@jblindsay thanks for your great answer.

**Comment by jblindsay** [comment]
Hi again am2222, I develop Whitebox GAT as a project that is tied to my own larger research program. That is, in my field of research I am deeply interested in developing and testing novel spatial analysis methods. Whitebox therefore serves as the platform for that development and test as well as for distributing my new methods to end-users. The fact that other people can use the results of this work for their own work and in creative (and sometimes surprising) ways, is always a wonderful thing to me. The University of Guelph does support the project in that it is recognized as part of my research contribution. That said, clearly with a million lines of written code, there is a lot of my personal time sunk into developing it as well ;-) 

I hope that answers your question.

**Comment by am2222** [comment]
@jblindsay  Thanks for your complete answer.
