### ISSUE TITLE
[bug report] Hillslope delineation algorithm.

### ISSUE THREAD

**Issue by crazyzlj** [jblindsay/whitebox-geospatial-analysis-tools#32]
Dear Prof. Lindsay,
First of all, thank for your brilliant work of the Whitebox GAT and the open-source project. Recently, I rewrite the hillslope delineation algorithm into my own project (A watershed modeling system named [SEIMS](https://github.com/lreis2415/SEIMS)) by Python. 
However, when I run with my study area data, an obvious bug occurred in handling the situation that converging points of two upstream are adjacent to the head stream cell of their downstream (e.g., Fig. 1). The result can be found in Fig. 2. 
![stream_with_flow_direction](https://user-images.githubusercontent.com/5744367/28452463-6a7316b2-6e25-11e7-9aa9-39918b697dad.png)
**Fig. 1 Example of stream link with the arrow indicates D8 flow direction**

![hillslope_result_of_whitebox](https://user-images.githubusercontent.com/5744367/28452836-0ebec242-6e27-11e7-8162-4e52be0f7c53.png)
**Fig.2 The hillslope result derived by Whitebox GAT 3.4.0.**

After careful review, I have implemented a correct version integrated into the preprocessing script of SEIMS in Python.  The result is shown in Fig. 3. The script can be found [here](https://github.com/lreis2415/SEIMS/blob/master/seims/preprocess/sd_hillslope.py). 

![hillslope_result_of_seims](https://user-images.githubusercontent.com/5744367/28452848-17436346-6e27-11e7-9be9-1c52f6f00abb.png)
**Fig. 3 The hillslope result derived by SEIMS.**

Since I am not family with Java, I have not a development environment to fix this bug in your code. Here is the workflow of my code:
+ Assign a unique id to each stream link if needed
+ Assign hillslope code for the 3*3 neighbors of each stream cell (assign_hillslope_code_of_neighbors() function)
  + Count the inflow stream cell number (in_strm_num) and coordinates of all inflow cells
  + If in_strm_num is 0, means this is a first-order stream head, then set all inflow cells to head hillslope code
  + Else means this is a conjunction. There are three steps to handle the situation:
    + From the clockwise direction of current slope direction to search for an inflow stream cell. Before an inflow stream cell is reached, set other inflow cells to right hillslope code;
    + From the counter-clockwise to search, and set other inflow cells to left hillslope code;
    + Finally, if still exist any non-stream inflow cells, set them as head hillslope code.
+ Routing from each cell to its downstream until a valid hillslope code is encountered, and set this code to the routes
+ ReAssign the stream cells value according to the different stream value assignment method.
+ Output the hillslope raster file.

I am looking forward to your revision. Thank you very much.
Best wishes,
Liangjun

**Comment by jblindsay** [comment]
Hello Liangjun,

What remarkable timing you have! I just discovered this bug myself four days ago when I was re-writing the hillslope algorithm for the new WhiteboxTools library, which will be replacing the current Java tools of Whitebox soon. I came up with a solution that is similar to your own, which you will find in this rust code:

[https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/master/whitebox_tools/src/tools/hydro_analysis/hillslopes.rs](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/master/whitebox_tools/src/tools/hydro_analysis/hillslopes.rs)

If you wish, give the WhiteboxTools' Hillslope tool a try and see if it works appropriately for your dataset. I tested it on three different datasets and found that in each case it fixed the issue of hillslopes at narrow confluences that was observed in with the Java tool.

**Comment by crazyzlj** [comment]
Hello, Prof. Lindsay,
It is so surprising and amazingly for your rapid reply and our magic synchronization on this algorithm. Rust is the first time I heard and seems to be a promising language. Your continuous innovation work is so admirable.
As far as I can see from the source code, this bug is fixed! I will follow the install instructions of WhiteboxTools and test this tool later.
BTW, hope to able to contribute more to Whitebox project in the future.
Thanks again.

**Comment by jblindsay** [comment]
Your contributions would be very welcome indeed!
