### ISSUE TITLE
GeoTIFF file import error

### ISSUE THREAD

**Issue by sbhadra019** [jblindsay/whitebox-geospatial-analysis-tools#43]
I am new to Whitebox GAT. While importing a GeoTIFF it says:

> An error has occurred during operation. See log files for details.

I have opened the log file from the install directory and failed to understand why this is giving an error. The GeoTIFF file worked ok in other software packages, i.e., TauDEM, ArcGIS. Here is the log file snap.
![image](https://user-images.githubusercontent.com/32178991/35066956-ef1a2dba-fb97-11e7-8aa7-e578e34354e0.png)
Thanks in advance.

**Comment by jblindsay** [comment]
The GeoTiff support in the current version of Whitebox GAT is not feature full. There are many versions of the GeoTiff format that are not supported. The new backend that we are developing for Whitebox, [WhiteboxTools](http://www.uoguelph.ca/~hydrogeo/software.shtml#WhiteboxTools), has more robust and improved support for reading and writing the GeoTiff format. It will be a while before we are able to release a version of Whitebox GAT with the new [WhiteboxTools](http://www.uoguelph.ca/~hydrogeo/software.shtml#WhiteboxTools) backend. In the meantime, I would suggest using WhiteboxTools (download [here](http://www.uoguelph.ca/~hydrogeo/software.shtml#WhiteboxTools)) directly for any GeoTiff operations (e.g. import/export).
