### ISSUE TITLE
[whitebox tools] Missed option in ExtractRasterStatistics

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-geospatial-analysis-tools#45]
ExtractRasterStatistics tool has parameter `--stat` which according to the tool help can accept one of the following values: "average", "minimum", "maximum", "range", "standard deviation", "total". However its default value "mean" not listed in the available options lists. IMHO this is a bit confusing.

**Comment by jblindsay** [comment]
Fixed with commit: [17da33080fbc1ddf0a577b92f6d77cfc0269defd](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/commit/17da33080fbc1ddf0a577b92f6d77cfc0269defd)
