### ISSUE TITLE
Add required vector geometry type to JSON output

### ISSUE THREAD

**Issue by alexbruy** [jblindsay/whitebox-geospatial-analysis-tools#48]
As I can see, initiall support for vector files already added, e.g. in "Watershed" tool there is a vector parameter. Hope in future we will see more tools operating on vectors and/or producing vectors.

While there is only a small number of such tools, I want to propose small feature: it would be nice to know not only that parameter is a vector file, but also which geometry type it should have (point, line etc). Of course, if this is not too difficult and fits into WhiteBox Tools philosophpy.

**Comment by jblindsay** [comment]
@alexbruy This is a good idea. I suppose it would be implemented using WhiteboxTool's parametering system. This may be a significant alteration to this, but I'll look into the feasibility. My only major concern is that it makes most sense when we can assume that the input vector file only contains one geometry type, such as is the case with the Shapefile format. As I eventually hope to add vector support for formats beyond the Shapefile, how will this geometry type specification affect that? Also, it'll have to be flexible enough to allow for multiple geometry type specifications as some tool can accept input vectors of more than one type.

**Comment by alexbruy** [comment]
> As I eventually hope to add vector support for formats beyond the Shapefile, how will this geometry type specification affect that?

Maybe I'm wrong, but in usually layers have single geometry type. From my experience multiple geometry columns is rather exception than rule.

As possible solution, a flag (or default functionality) can be added to skip incompatible geometries.

> Also, it'll have to be flexible enough to allow for multiple geometry type specifications as some tool can accept input vectors of more than one type.

I see, we have similar problem in QGIS Processing: some tools work with any geometry type and some are restricted to single geometry type. We solved it by introducing parameter which is a list of supported geometry types, e.g. `Point, Line`. Also we have an `AnyGemetry` specifier.

Hope this helps a bit.

**Comment by jblindsay** [comment]
I believe that the GeoJSON format allows for multiple geometry types in a single file. I don't know of other such formats but admittedly I'm not overly familiar with the state-of-the-science here. As I said in a parallel comment, file formats kind of give me a shutter when I think about the variety and complexity of some of them.

As for the AnyGeometry, that is exactly what I was thinking of as a way of handling tools that can accept multiple geometry types as well. I'll investigate this a little further.

**Comment by alexbruy** [comment]
> I believe that the GeoJSON format allows for multiple geometry types in a single file. I don't know of other such formats

If I'm not wrong, MapInfo's TAB format also allows to mix multiple geometry types in the same layer, as well as DFX/DWG.

> As for the AnyGeometry, that is exactly what I was thinking of as a way of handling tools that can accept multiple geometry types as well. I'll investigate this a little further.

From my experience with QGIS, there is one case when AnyGeometry geometry is not ideal choice and better to explicitly define expected geometry types: for example some operations don't work with points, but can be applied to lines and polygons. Other combinations also possible. I agree that probably some research is needed here.

**Comment by jblindsay** [comment]
As I'm starting to add support for vectors and am (hopefully) soon to add tools that take vector inputs/outputs, it will be very important that I think about these types of things from the outset so that I spend less time and effort retrofitting them later when it becomes apparent that they need to be added. So I thank you for bringing this up and I'll certainly add it to my to-do list of features to add. I'll let you know when I have a working prototype and hopefully you can provide some feedback if you think it works well with the QGIS plugin. Thanks again.

**Comment by jblindsay** [comment]
@alexbruy I've added support for giving hints as to the required vector geometry type in the tool parameters. See [here](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/a4c8e195af5cad594e023754f1a1abfecd589808/whitebox_tools/src/tools/mod.rs#L959) and the example [here](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/a4c8e195af5cad594e023754f1a1abfecd589808/whitebox_tools/src/tools/stream_network_analysis/long_profile_from_points.rs#L57). Hopefully the crude categories of Any, Points, Lines, and Polygons is sufficient, but if you think that it could be further refined, please let me know and I'll adjust as needed. I'm closing this issue now as solved.

**Comment by alexbruy** [comment]
@jblindsay cool! Thanks a lot! I will update provider ASAP.
