### ISSUE TITLE
Tool "Extend Vector Lines" fails

### ISSUE THREAD

**Issue by pathmapper** [jblindsay/whitebox-geospatial-analysis-tools#50]
Hi, 

I am trying to use the the tool `Extend Vector Lines` on a line shapfile, but it isn't working.

Version: Whitebox GAT 3.4 'Montreal'
OS: Linux and Windows

![image](https://user-images.githubusercontent.com/20856381/36425811-4d4851e4-1648-11e8-9d3c-4a884a9e3b25.png)

![image](https://user-images.githubusercontent.com/20856381/36425704-d74189c0-1647-11e8-9018-68c0f1699bae.png)

Please find attached the shapefile and the error log.
[lines_whitebox.zip](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/files/1740138/lines_whitebox.zip)

Any idea what is causing the error and how to solve it?
Thank you!

**Comment by pathmapper** [comment]
OK, the cause of the error is that the geometry type of the input shapefile is `LineStringZ`.

After conversion to geometry type `LineString` (without z-dimension) it works as intended.

Thanks a lot for your work with Whitebox!

**Comment by jblindsay** [comment]
I'm glad that you were able to make it work for ypu.
