### ISSUE TITLE
Tool "Extend Vector Lines" CRS (.prj) for output file missing

### ISSUE THREAD

**Issue by pathmapper** [jblindsay/whitebox-geospatial-analysis-tools#51]
The tool "Extend Vector Lines" works very well!

One thing I've noticed:
When a CRS for the input shapefile is defined via a .prj file, a corresponding .prj file for the output shapefile is missing.

**Comment by jblindsay** [comment]
@pathmapper  It's true that the .prj file is not output from any of Whitebox's tools. In truth, Whitebox doesn't currently handle projection information particularly well. Hopefully this can be rectified as I'm developing the new analytical backend, WhiteboxTools, although I'm only now adding support for vector data and a map projection utility may be some ways off.

**Comment by pathmapper** [comment]
Thanks for your reply @jblindsay! 

Currently I am using only the Whitebox tool "Extend Vector Lines" (FYI: found it because of this post: https://gis.stackexchange.com/a/111900/105333), but I will have a deeper look at Whitebox for sure.
I also find WhiteboxTools very interesting and I'm planning to try out some tools with some scripts.

The missing .prj file isn't a problem for me since I'm able to reassign the projection after the use of "Extend Vector Lines".

I was just thinking that maybe it would be a quick fix to take the CRS from the input shapefile and assign it to the output shapefile, so please feel free to close this issue if this is nothing on your priority list.

Thanks again for your work!

**Comment by jblindsay** [comment]
@pathmapper I've just committed a fix to the repo that should copy the projection file of the input file for the output created by the tool. See [here](https://github.com/jblindsay/whitebox-geospatial-analysis-tools/blob/92e4852c6a80f6800dc2d5e12ed4b977f35033ac/resources/plugins/Scripts/ExtendVectorLines.groovy#L125) for details. You can download the script file in the repository and just replace the script in your plugins => Scripts directory and relaunch Whitebox. This is just a quick fix for your specific problem, but it does not address the larger issue that currently Whitebox's tools don't handle projection information by default. As tools are ported to the new WhiteboxTools back-end, I'll keep this current limitation in mind and aim to rectify the situation. I am only now adding support for vector data and so this is a good time to be thinking about such things.

**Comment by pathmapper** [comment]
Thanks @jblindsay, the fix works perfectly!

**Comment by jblindsay** [comment]
I'm glad to hear @pathmapper. Thanks for the feedback.
