### ISSUE TITLE
Error while using Remove off terrain points using whitebox processing plugin in Qgis

### ISSUE THREAD

**Issue by vipin-k-singhal** [jblindsay/whitebox-geospatial-analysis-tools#53]
I applied ROTO to DEM data to remove off terrain points/objects with Filter parameter set to 11 and Slope parameter set to 15, But i am getting an error while running the algorithm.
I found the following error while looking at log file 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:335:21

**Comment by jblindsay** [comment]
I'm afraid that this issue has been linked to the wrong repository. You are looking for https://github.com/jblindsay/whitebox-tools/ instead. Despite their confusingly similar names, WhiteboxTools is the stand-alone geospatial library that the QGIS plugin is based upon. Whitebox GAT is the full-featured GIS, with user-interface.
