### ISSUE TITLE
Whitebox and QGIS 3.4

### ISSUE THREAD

**Issue by geosystems** [jblindsay/whitebox-geospatial-analysis-tools#63]
I'm trying to run some tools from the whitebox processing  within the QGIS processing environment.
For all the process I got a common error (following there is the window I got for the "Apect" but for the other tools the results are the same) which tells that "thread 'main' panicked at 'it is impossible to find the specified path'.....

I've tried to find a solution by myself but nothing happen. I've installed both the plugin and also the Whitebox executable according to the guide and, apparently, everything is fine except when the single tools are executed.

TEXT OF THE ERROR FOLLOWING:

WhiteBoxTools command output:
*********************

* Welcome to Aspect *

*********************

Reading data...

thread 'main' panicked at 'Impossibile trovare il percorso specificato. (os error 3)', src\main.rs:66:21

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Esecuzione completata in 0.22 secondi
Risultati:
{'output': <QgsProcessingOutputLayerDefinition {'sink':C:/Users/UTENTE/AppData/Local/Temp/processing_d5fa984e2b9c42aea2edd9adc21546be/e78363a9fc064dc3958144c243e1d9cc/output.tif, 'createOptions': {'fileEncoding': 'System'}}>}

**Comment by dbreckon** [comment]
x2 having the exact same issue

**Comment by jblindsay** [comment]
This issue should be reported in the [WhiteboxTools](https://github.com/jblindsay/whitebox-tools) repository and not the Whitebox Geospatial Analysis Tools repository.

**Comment by jblindsay** [comment]
@dbreckon Are you using v1.0.2 of WhiteboxTools?

**Comment by dbreckon** [comment]
v0.16 with the Alex Bruy plugin

**Comment by dbreckon** [comment]
Windows

**Comment by jblindsay** [comment]
Alex Bruy's plugin is only a front-end for the WhiteboxTools executable. I am talking about updating the WhiteboxTools executable to v1.0.2, not the QGIS frontend. Please download the latest version of WhiteboxTools from the WhiteboxTools repo (not this one, which is a completely different software). Then update the QGIS front-end to point to this new executable (within Settings). Please let me know if that resolves your issue.

**Comment by dbreckon** [comment]
Will do and will post in WhiteboxTools next time.  Thank you

**Comment by jblindsay** [comment]
No problem. I'm keen to know if it works, so please email me directly if it does or open a new issue on the WhiteboxTools repo if it is still not working properly. Thanks.
