### ISSUE TITLE
Burn Streams At Roads not recognizing Polyline Shapefiles, but Burn Streams is?

### ISSUE THREAD

**Issue by zclifton** [jblindsay/whitebox-geospatial-analysis-tools#64]
Hi! Apologies in advance if this is something obvious, not sure if this is a script error or user error on my end, but here we go. 

I currently have two shapefiles loaded into WhiteBox GAT GUI, one for my streams (a sample of NHD flowlines clipped to my watershed boundaries) and one for my roads (also clipped to my watershed boundaries). I also have an elevation tif loaded. 

The issue occurs when I try to run the Burn Streams at Roads function. After selecting the .dep elevation file, the stream shapefile, and the roads shapefile, and specifying the road pixel width, an error message pops up saying "The input streams shapefile should be of a POLYLINE ShapeType". I doublechecked the metadata for said shapefile in ArcGIS (polyline), then checked it using the arcpy.Describe function (code snippet below of the print out). 

`import arcpy
>>> desc=arcpy.Describe("NHDFlowline_clas")
>>> desc.ShapeType
u'Polyline'
>>> `

However, the Burn Streams function also requires a POLYLINE stream shapefile, and seems to run just fine. I looked at the code for both functions, specifically where ( I think) they're reading in the input stream shapefiles, and noticed a difference: 

**Burn Streams At Roads**

`  // read the input parameters
            String demFile = args[0]
            String streamsFile = args[1]
            String roadsFile = args[2]
            String outputFile = args[3]
            double roadWidth = Double.parseDouble(args[4]) / 2.0

            ShapeFile streams = new ShapeFile(streamsFile)
			ShapeType shapeType = streams.getShapeType()
            if (shapeType != ShapeType.POLYLINE) {
            	pluginHost.showFeedback("The input streams shapefile should be of a POLYLINE ShapeType.")
            	return
            }
`

**Burn Streams**
`        // check to see that the inputHeader and outputHeader are not null.
        if ((demHeader == null) || (inputStreamsFile == null) || (outputHeader == null)) {
            showFeedback("One or more of the input parameters have not been set properly.");
            return;
        }

        try {
            DEM = new WhiteboxRaster(demHeader, "r");
            rows = DEM.getNumberRows();
            cols = DEM.getNumberColumns();
            noData = DEM.getNoDataValue();
            gridRes = (DEM.getCellSizeX() + DEM.getCellSizeY()) / 2;

            if (inputStreamsFile.toLowerCase().endsWith(".dep")) {
                streamsHeader = inputStreamsFile;
                streams = new WhiteboxRaster(streamsHeader, "r");
            } else if (inputStreamsFile.toLowerCase().endsWith(".shp")) {
                streamsHeader = inputStreamsFile.replace(".shp", "_temp.dep");

                // convert the streams vector into a temporary raster
                // initialize the shapefile input
                ShapeFile input = new ShapeFile(inputStreamsFile);
                int numRecs = input.getNumberOfRecords();

                if (input.getShapeType() != ShapeType.POLYLINE
                        && input.getShapeType() != ShapeType.POLYLINEZ
                        && input.getShapeType() != ShapeType.POLYLINEM
                        && input.getShapeType() != ShapeType.POLYGON
                        && input.getShapeType() != ShapeType.POLYGONZ
                        && input.getShapeType() != ShapeType.POLYGONM) {
                    showFeedback("The input shapefile must be of a 'polyline' or "
                            + "'polygon' data type.");
                    return;
                }

                // initialize the output raster
                streams = new WhiteboxRaster(streamsHeader, "rw",
                        demHeader, WhiteboxRasterBase.DataType.INTEGER, 0);

                streams.isTemporaryFile = true;
`

Could you elaborate on the code differences between the two during these initial stages and/or offer some suggestions to get around this issue? I'd be happy to send over the shapefile in question if needed.

**Comment by glegarec** [comment]
Hi! Have you found a workaround for this issue @zclifton ? I'm running into the same exact problem.

Thanks.

**Comment by zclifton** [comment]
I haven't, sorry! Best of luck

**Comment by jblindsay** [comment]
I suggest using the WhiteboxTools [BurnStreamsAtRoads](https://jblindsay.github.io/wbt_book/available_tools/hydrological_analysis.html#BurnStreamsAtRoads) instead. WhiteboxTools is where the current ongoing development is and Whitebox GAT is legacy code only at this point.
