### ISSUE TITLE
Coudld use more Getting Started and Troubleshooting info 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jblindsay/whitebox-geospatial-analysis-tools#9]
```
(((preface: terseness doesn't convey irritation, just lack of time)))

The "download"[0]  page says " Instructions for installing and running Whitebox 
can be found on the project’s main page.", but doesn't link to said main 
page. The top of that domain is a blog[1], which has many write ups of what one 
can do with Whitebox, but not on how to run it and what to do when things don't 
go as expected.

[0] http://whiteboxgeospatial.wordpress.com/download/
[1] http://whiteboxgeospatial.wordpress.com/

Unpacking the download archive (Whitebox_3_2_1) to a convenient location after 
updating the Java Runtime to v8 (jre-8u25-windows-x64.exe) on the same day and 
2x clicking on the .jar file does nothing (on my system: Win7x64). 


Running `C:\apps\Whitebox_3_2_1> java WhiteboxGIS.jar` on the command line 
yields "Error: Could not find or load main class WhiteboxGIS.jar"

Running `java -jar "WhiteboxGIS.jar"` is the same as double-click, nothing 
seems to happen.

The logs folder does have `LauncherLog0_0.xml` with a current timestamp 
contents are not revealing:

```
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2014-11-24T15:02:05</date>
  <millis>1416870125021</millis>
  <sequence>0</sequence>
  <logger>whiteboxgis</logger>
  <level>CONFIG</level>
  <class>whiteboxgis.Main</class>
  <method>launchProgram</method>
  <thread>1</thread>
  <message>sun.arch.data.model = 64</message>
</record>
<record>
  <date>2014-11-24T15:02:05</date>
  <millis>1416870125052</millis>
  <sequence>1</sequence>
  <logger>whiteboxgis</logger>
  <level>CONFIG</level>
  <class>whiteboxgis.Main</class>
  <method>startSecondJVM</method>
  <thread>1</thread>
  <message>HeapSize = -Xmx7G</message>
</record>
</log>
```


Java details:

```
C:\apps\Whitebox_3_2_1>java -version
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

Windows:

```
Windows 7 Professional x64
SP 1
12 GB Memory
dual E5420 2.5GHz CPUs
C: 32GB free
D: 13GB free
```

```

Original issue reported on code.google.com by `map...@gmail.com` on 25 Nov 2014 at 4:41

**Comment by jblindsay** [comment]
Links have been added to the Whitebox GAT blog download site.
